site_name: Pignio Docs
site_url: https://octospacc.github.io/Pignio/
repo_url: https://gitlab.com/octospacc/Pignio
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: docs/.overrides
  language: en
  features:
    - content.action.view
    - content.action.edit
    - content.code.copy
    - navigation.tabs
  palette:
    - primary: pink
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - primary: pink
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - awesome-nav
  - blog
  - ezlinks
  - glightbox:
      auto_caption: true
  - link-preview
  - meta
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
  - offline
  - open-in-new-tab
  - rss:
      date_from_meta:
        as_creation: "date"
        as_update: "git"
  - search
  - tags
markdown_extensions:
  - pymdownx.extra
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      use_pygments: true
  - pymdownx.magiclink
  - pymdownx.tasklist
extra_css:
  - link-preview.css
